name: Dotnet workflow

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

env:
  NODE_VERSION: '13.x'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source tree
        uses: actions/checkout@v2
      #- name: Setup bazelisk
      #  uses: ./.github/actions/setup-bazelisk
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'         
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      #- uses: ./.github/actions/setup-bazelisk
          
      - name: Build grid
        uses: ./.github/actions/bazel
        with:
          command: build -s //dotnet/src/webdriver:netstandard2.0
          #command: build //dotnet/source/common:chrome
